_common: &common
  env_type: SpatialGym
  max_actions_per_traj: 1
  env_instruction: "You are solving a spatial question."
  max_tokens: 256

# prompt
_prompt_standard: &prompt_standard
  prompt_config:
    topdown: false
    cogmap: false
    type: standard

_prompt_cogmap: &prompt_cogmap
  prompt_config:
    topdown: false
    cogmap: true
    type: standard
  cogmap_config:
    cogmap_type: standard
    pos_allow_scale: true
    scope: all

_prompt_topdown: &prompt_topdown
  prompt_config:
    topdown: true
    cogmap: false
    type: standard

# exp_type
_passive: &passive
  exp_type: passive
  n_objects: 8
  level: 2 # 0, 1, 2
  main: 5 # 12, 7, 5
  room_size: [20, 20]
  proxy_agent_config:
    type: analyst
    delegate: observer_analyst
    observer_delegate: strategist


_active: &active
  exp_type: active
  n_objects: 8
  max_exp_steps: 15
  room_size: [15, 15]
  level: 2
  main: 6

custom_envs:
  PassiveDir:
    <<: *common
    env_config:
      <<: *prompt_standard
      <<: *passive
      name: "passive_dir"
      eval_tasks: [{task_type: "dir", task_kwargs: {}}]

  PassiveRot:
    <<: *common
    env_config:
      <<: *prompt_standard
      <<: *passive
      name: "passive_rot"
      eval_tasks: [{task_type: "rot", task_kwargs: {}}]

  PassiveRotDual:
    <<: *common
    env_config:
      <<: *prompt_standard
      <<: *passive
      name: "passive_rot_dual"
      eval_tasks: [{task_type: "rot_dual", task_kwargs: {}}]

  PassiveLoc:
    <<: *common
    env_config:
      <<: *prompt_standard
      <<: *passive
      name: "passive_loc"
      eval_tasks: [{task_type: "loc", task_kwargs: {'only_main_room': False}}]

  PassiveE2A:
    <<: *common
    env_config:
      <<: *prompt_standard
      <<: *passive
      name: "passive_e2a"
      eval_tasks: [{task_type: "e2a", task_kwargs: {}}]

  PassivePoV:
    <<: *common
    env_config:
      <<: *prompt_standard
      <<: *passive
      name: "passive_pov"
      eval_tasks: [{task_type: "pov", task_kwargs: {}}]

  PassiveFalseBelief:
    <<: *common
    env_config:
      <<: *prompt_standard
      <<: *passive
      name: "passive_false_belief"
      eval_tasks: [{task_type: "false_belief", task_kwargs: {}}]

  PassiveBwdNav:
    <<: *common
    env_config:
      <<: *prompt_standard
      <<: *passive
      name: "passive_bwd_nav"
      eval_tasks: [{task_type: "bwd_nav", task_kwargs: {}}]

  PassiveFwdFov:
    <<: *common
    env_config:
      <<: *prompt_standard
      <<: *passive
      name: "passive_fwd_fov"
      eval_tasks: [{task_type: "fwd_fov", task_kwargs: {}}]
  

  PassiveDirCogmap:
    <<: *common
    env_config:
      <<: *prompt_cogmap
      <<: *passive
      name: "passive_dir_cogmap"
      eval_tasks: [{task_type: "dir", task_kwargs: {}}]

  PassiveRotCogmap:
    <<: *common
    env_config:
      <<: *prompt_cogmap
      <<: *passive
      name: "passive_rot_cogmap"
      eval_tasks: [{task_type: "rot", task_kwargs: {}}]

  PassiveLocCogmap:
    <<: *common
    env_config:
      <<: *prompt_cogmap
      <<: *passive
      name: "passive_loc_cogmap"
      eval_tasks: [{task_type: "loc", task_kwargs: {}}]


  ActiveDir:
    <<: *common
    max_actions_per_traj: 25
    env_config:
      <<: *prompt_standard
      <<: *active
      name: "active_dir"
      eval_tasks: [{task_type: "dir", task_kwargs: {}}]

  ActiveRot:
    <<: *common
    max_actions_per_traj: 25
    env_config:
      <<: *prompt_standard
      <<: *active
      name: "active_rot"
      eval_tasks: [{task_type: "rot", task_kwargs: {}}]

  ActiveLoc:
    <<: *common
    max_actions_per_traj: 25
    env_config:
      <<: *prompt_standard
      <<: *active
      name: "active_loc"
      eval_tasks: [{task_type: "loc", task_kwargs: {}}]

  ActiveDirCogmap:
    <<: *common
    max_actions_per_traj: 25
    env_config:
      <<: *prompt_cogmap
      <<: *active
      name: "active_dir_cogmap"
      eval_tasks: [{task_type: "dir", task_kwargs: {}}]

  ActiveRotCogmap:
    <<: *common
    max_actions_per_traj: 25
    env_config:
      <<: *prompt_cogmap
      <<: *active
      name: "active_rot_cogmap"
      eval_tasks: [{task_type: "rot", task_kwargs: {}}]

  ActiveLocCogmap:
    <<: *common
    max_actions_per_traj: 25
    env_config:
      <<: *prompt_cogmap
      <<: *active
      name: "active_loc_cogmap"
      eval_tasks: [{task_type: "loc", task_kwargs: {}}]

  
