model_info:
  Qwen2.5-7B-Instruct:
    provider_name: together
    model_name: Qwen/Qwen2.5-7B-Instruct-Turbo
    generation_kwargs:
      temperature: 0
      max_tokens: 1024
  Qwen2.5-72B-Instruct:
    provider_name: together
    model_name: Qwen/Qwen2.5-72B-Instruct-Turbo
    generation_kwargs:
      temperature: 0
      max_tokens: 1024
  claude-3.7:
    provider_name: anthropic
    model_name: claude-3-7-sonnet-20250219
    generation_kwargs:
      temperature: 0
      max_tokens: 1024
  gpt-4o:
    provider_name: openai
    model_name: gpt-4o
    generation_kwargs:
      temperature: 0
      max_tokens: 1024
  o1-mini:
    provider_name: openai
    model_name: o1-mini
    generation_kwargs:
      temperature: 1 # o1-mini does not support temperature = 0
      max_completion_tokens: 4096 # including thinking tokens
  o3-mini:
    provider_name: openai
    model_name: o3-mini
    generation_kwargs:
      temperature: 1
      max_completion_tokens: 8192
  o4-mini:
    provider_name: openai
    model_name: o4-mini
    generation_kwargs:
      temperature: 1
      max_completion_tokens: 4096
