model_info:
  Qwen2.5-7B-Instruct:
    provider_name: together
    model_name: Qwen/Qwen2.5-7B-Instruct-Turbo
    generation_kwargs:
      temperature: 0
      max_tokens: 8192
  Qwen2.5-72B-Instruct:
    provider_name: together
    model_name: Qwen/Qwen2.5-72B-Instruct-Turbo
    generation_kwargs:
      temperature: 0
      max_tokens: 8192
  Qwen3-235B-A22B-Thinking-2507:
    provider_name: together
    model_name: Qwen/Qwen3-235B-A22B-Thinking-2507
    generation_kwargs:
      temperature: 0
      max_tokens: 8192
  claude-3.7-sonnet:
    provider_name: anthropic
    model_name: claude-3-7-sonnet-20250219
    generation_kwargs:
      temperature: 0
      max_tokens: 8192
  claude-4-sonnet:
    provider_name: anthropic
    model_name: claude-sonnet-4-20250514
    generation_kwargs:
      temperature: 0
      max_tokens: 8192
  deepseek-r1:
    provider_name: deepseek
    model_name: deepseek-reasoner
    generation_kwargs:
      temperature: 0
      max_completion_tokens: 8192
  deepseek-v3:
    provider_name: deepseek
    model_name: deepseek-chat
    generation_kwargs:
      temperature: 0
      max_completion_tokens: 8192
  gpt-4o:
    provider_name: openai
    model_name: gpt-4o
    generation_kwargs:
      temperature: 0
      top_p: 1
      seed: 42
      max_tokens: 8192
  gpt-4.1-nano:
    provider_name: openai
    model_name: gpt-4.1-nano
    generation_kwargs:
      temperature: 0
      max_tokens: 8192
  gpt-4.1-mini:
    provider_name: openai
    model_name: gpt-4.1-mini
    generation_kwargs:
      temperature: 0
      max_tokens: 2048
  gpt-4.1:
    provider_name: openai
    model_name: gpt-4.1
    generation_kwargs:
      temperature: 0
      max_tokens: 8192
  gpt-5:
    provider_name: openai
    model_name: gpt-5
    generation_kwargs:
      temperature: 1
      max_completion_tokens: 16384
  gpt-5-nano:
    provider_name: openai
    model_name: gpt-5-nano
    generation_kwargs:
      temperature: 1
      max_completion_tokens: 16384
  gpt-5-mini:
    provider_name: openai
    model_name: gpt-5-mini
    generation_kwargs:
      temperature: 1
      max_completion_tokens: 16384
  o3-mini:
    provider_name: openai
    model_name: o3-mini
    generation_kwargs:
      temperature: 1
      max_completion_tokens: 8192
  o4-mini:
    provider_name: openai
    model_name: o4-mini
    generation_kwargs:
      temperature: 1
      max_completion_tokens: 8192
  gpt-oss-20b:
    provider_name: openai
    model_name: openai/gpt-oss-20b
    generation_kwargs:
      temperature: 0
      max_tokens: 16384
  gemini-2.5-pro:
    provider_name: google
    model_name: gemini-2.5-pro
    generation_kwargs:
      temperature: 0
      max_completion_tokens: 8192
  gemini-2.5-flash:
    provider_name: google
    model_name:  gemini-2.5-flash
    generation_kwargs:
      temperature: 0
      max_completion_tokens: 8192
  gemini-2.0-flash:
    provider_name: google
    model_name:  gemini-2.0-flash
    generation_kwargs:
      temperature: 0
      max_completion_tokens: 8192
  GLM-4.5-Air:
    provider_name: openai
    model_name:  zai-org/GLM-4.5-Air
    generation_kwargs:
      temperature: 0
      max_completion_tokens: 8192 
  Kimi-K2-Instruct:
    provider_name: openai
    model_name:  moonshotai/Kimi-K2-Instruct
    generation_kwargs:
      temperature: 0
      max_completion_tokens: 8192
  MiniMax-M1-80k:
    provider_name: openai
    model_name: MiniMaxAI/MiniMax-M1-80k
    generation_kwargs:
      temperature: 0
      max_completion_tokens: 8192

      