tags: 
  - ActiveRot

num: 1

override: false  # whether to use active explore history, only valid when task is active task

defaults:
  - base
  - envs_spatial
  - evaluate_api_llm

output_dir: results/gpt-5-mini/debug

eval_model_type: api # api or vllm
# api model
api_model_info:
  model_name: gpt-4.1-mini # o4-mini
  max_concurrency: 128

# vllm model
model_path: Qwen/Qwen2.5-3B-Instruct
actor_rollout_ref:
  rollout:
    max_model_len: 10000
    gpu_memory_utilization: 0.8
    val_kwargs: # for vllm
      temperature: 0
      top_p: 1

agent_proxy:
  max_turn: 20 # should be same as max_actions_per_traj
  action_sep: "||"
  max_actions_per_turn: 1 # how many actions can be output at most in a single turn
  enable_think: true

es_manager:
  val:
    env_groups: ${mul:${len:${tags}}, ${num}}
    group_size: 1
    env_configs:
        # tags: ["PassiveRot", "PassiveRotDual", "PassivePoV", "PassiveDir", "PassiveE2A", "PassiveLoc", "PassiveFalseBelief"]

      tags: ${tags}
      n_groups: ${repeat:${num}, ${len:${tags}}}
